"""changeds

Revision ID: 3063abbfd07d
Revises: 8cd65597a45d
Create Date: 2025-04-14 19:17:55.154129

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3063abbfd07d'
down_revision = '8cd65597a45d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('strategy')
    op.drop_table('operator')
    op.drop_table('map')
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('map_image_url', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('drawing_image_url', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_column('drawing_image_url')
        batch_op.drop_column('map_image_url')

    op.create_table('map',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('map_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='map_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('operator',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('speed', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('armor', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ability_description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='operator_pkey')
    )
    op.create_table('strategy',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('map_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('site', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('role', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['map_id'], ['map.id'], name='strategy_map_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='strategy_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='strategy_pkey')
    )
    # ### end Alembic commands ###
