"""added notes to project

Revision ID: 8da87cdf13a9
Revises: adaef549d01f
Create Date: 2025-04-14 21:53:46.900406

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8da87cdf13a9'
down_revision = 'adaef549d01f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Project', schema=None) as batch_op:
        batch_op.drop_column('notes')

    # ### end Alembic commands ###
