"""create Project table

Revision ID: adaef549d01f
Revises: 3063abbfd07d
Create Date: 2025-04-14 21:00:12.906461

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'adaef549d01f'
down_revision = '3063abbfd07d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project', sa.String(length=100), nullable=False),
    sa.Column('map', sa.String(length=100), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.Column('characters', sa.PickleType(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('project')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('map', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('characters', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('map_image_url', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('drawing_image_url', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='project_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='project_pkey')
    )
    op.drop_table('Project')
    # ### end Alembic commands ###
